classifier: random_forest
drop_cols:
- Name
- Cabin
- Ticket
- Sex
- Age
- Fare
- Embarked
- Pclass Sex
- Pclass Age
- Pclass SibSp
- Pclass Parch
- Pclass Fare
- Pclass Embarked
- Sex Age
- Sex SibSp
- Sex Parch
- Sex Fare
- Sex Embarked
- Age SibSp
- Age Parch
- Age Fare
- Age Embarked
- SibSp Parch
- SibSp Fare
- SibSp Embarked
- Parch Fare
- Parch Embarked
- Fare Embarked
- family_size
- is_vip
- parent
- is_orphan
- is_single_adult_mother
- is_single_adult_male
dtypes:
  Age: float
  Embarked: category
  Fare: float
  Parch: int
  Pclass: category
  Sex: category
  SibSp: int
  Survived: category
feature_eng:
  featurize: true
imputation:
  Age: 29.6991
  Fare: 32.2042
  method: mean
model_params:
  logistic_regression:
  naive_bayes:
  neural_network:
  random_forest:
    criterion: gini
    max_depth: 15
    max_features: auto
    min_samples_leaf: 6
    min_samples_split: 9
    n_estimators: 460
  support_vector_machine:
  xgboost:
normalize:
param_tuning:
  logistic_regression:
  naive_bayes:
  neural_network:
  num_eval: 100
  random_forest:
    criterion: gini
    max_depth: 15
    max_features: auto
    min_samples_leaf: 6
    min_samples_split: 9
    n_estimators: 460
  scoring: accuracy
  support_vector_machine:
predict:
  js_estimator: true
random_seed: 12345
train_test_split:
  n_split: 10
  shuffle: true
  target_class: Survived
